#!/bin/bash

function fail() {
    echo "Error: ${*}"
    exit 1
}

cd "$(dirname "$0")" || exit 1

while getopts "f" o; do
    case "$o" in
        "f") FORCE_REINSTALL=1 ;;
        *) ;;
    esac
done
shift $((OPTIND - 1))

MODULES="$(grep -v '#' "enabled")"
RC_FILE=".zshrc"
COMBINED_RC=""

for module in $MODULES; do
    DEPS="${module}/_dependencies"
    INSTALL="${module}/_install.sh"
    RC="${module}/_rc"

    if [ -f "$DEPS" ]; then
        while read -r dependency; do
            which "$dependency" 1>/dev/null || fail "Missing dependency : ${dependency}"
        done <"$DEPS"
    fi

    if [ -f "$RC" ]; then
        COMBINED_RC="${COMBINED_RC}\n\n$(cat "$RC")"
    fi

    if [ -f "$INSTALL" ]; then
        if ! which -s "$module" || [ -n "$FORCE_REINSTALL" ]; then
            echo "Installing: ${module}"
            eval "$INSTALL" 1>/dev/null 2>/dev/null
        fi
    fi

    case "$module" in
        "zsh") cp "${module}/${RC_FILE}" "${HOME}/${RC_FILE}" ;;
        *)
            [ ! -d "${module}" ] && {
                echo "Warning: ${module} is enabled but not found"
                continue
            }
            MOD_CONFIG="$(find "$module" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)"
            while read -r config; do
                [ -z "$config" ] && continue
                CONFIG_LOC="${HOME}/${config//_//}"
                TARGET="${PWD}/${module}/${config}"

                [ -e "${CONFIG_LOC}" ] && rm "${CONFIG_LOC}"
                ln -s "${TARGET}" "${CONFIG_LOC}"
            done <<<"$MOD_CONFIG"
            ;;
    esac
done

COMBINED_RC="$(echo -e "$COMBINED_RC")"
grep "alias=" <<<"$COMBINED_RC" >>"${HOME}/${RC_FILE}"
grep -v "alias=" <<<"$COMBINED_RC" >>"${HOME}/${RC_FILE}"

# shellcheck source=../.zshrc
source "${HOME}/${RC_FILE}" 2>/dev/null
